l_english:

### Vanilla KRR Nation Buffs ###
  custom_diff_strong_can:0 "£KR_game_rule_flag_CAN   Strengthen the Dominion of Canada"
  custom_diff_strong_csa:0 "£KR_game_rule_flag_CSA   Strengthen the Combined Syndicates of America"
  custom_diff_strong_tex:0 "£KR_game_rule_flag_TEX   Strengthen the American Union State"
  custom_diff_strong_cal:0 "£KR_game_rule_flag_CAL   Strengthen the Pacific States of America"
  custom_diff_strong_nee:0 "£KR_game_rule_flag_NEE   Strengthen New England"
  custom_diff_strong_rus:0 "£KR_game_rule_flag_RUS   Strengthen the Russian Republic"
  custom_diff_strong_trm:0 "£KR_game_rule_flag_TRM   Strengthen Transamur"
### New Nation Buffs
  custom_diff_strong_gre:0 "@GRE   Strengthen the Hellenic State"
  custom_diff_strong_dkb:0 "@DKB   Strengthen the Don-Kuban Union"
