NDefines.NGame.START_DATE	= "0975.1.2.12"
NDefines.NGame.END_DATE		= "0990.6.6.6"
NDefines.NGame.MAP_SCALE_PIXEL_TO_KM = 100
NDefines.NAI.MAX_DISTANCE_NALAV_INVASION = 9000.0
NDefines.NBuildings.MAX_SHARED_SLOTS = 50
NDefines.NProduction.MAX_CIV_FACTORIES_PER_LINE = 20
NDefines.NCountry.POLITICAL_POWER_CAP = 2000.0
NDefines.NNavy.DETECTION_CHANCE_MULT_BASE = 0.3
NDefines.NNavy.VISIBILITY_MULTIPLIER_FOR_SPOTTING = 1.0
NDefines.NNavy.BASE_SPOTTING_SPEED = 10.0
NDefines.NNavy.NAVAL_INVASION_PREPARE_HOURS = 20
NDefines.NNavy.NAVAL_SPEED_MODIFIER = 30.0
NDefines.NNavy.NAVAL_SUPREMACY_CAN_INVADE = 0.4
NDefines.NNavy.NAVAL_TRANSFER_BASE_SPEED = 75.0
NDefines.NNavy.AMPHIBIOUS_INVADE_SPEED_BASE = 3.0
NDefines.NNavy.NAVAL_RANGE_TO_INGAME_DISTANCE = 3.0
AGGRESSION_SETTINGS_VALUES = {
50.0,
200.0,
400.0,
500.0,
10000,
}
NDefines.NDiplomacy.VOLUNTEERS_PER_TARGET_PROVINCE = 0.20
NDefines.NDiplomacy.VOLUNTEERS_PER_COUNTRY_ARMY = 0.25
NDefines.NDiplomacy.VOLUNTEERS_TRANSFER_SPEED = 10
NDefines.NDiplomacy.VOLUNTEERS_DIVISIONS_REQUIRED = 15
NDefines.NPolitics.ARMY_LEADER_COST = 500

NDefines.NDiplomacy.ASSUME_FACTION_LEADERSHIP_PP_COST = 10000
NDefines.NDiplomacy.ASSUME_FACTION_LEADERSHIP_MIN_MANPOWER_RATIO = 600
NDefines.NDiplomacy.ASSUME_FACTION_LEADERSHIP_MIN_FACTORY_RATIO = 600
NDefines.NDiplomacy.ASSUME_FACTION_LEADERSHIP_COOLDOWN_DAYS = 180
NDefines.NDiplomacy.ASSUME_FACTION_SPYMASTER_COOLDOWN_DAYS = 180
NDefines.NDiplomacy.FACTION_LEADERSHIP_CHANGE_ALERT_THRESHOLD = 1
NDefines.NDiplomacy.DIPLOMACY_CREATE_FACTION_FACTOR = 0.40

NDefines.NAir.AIR_WING_FLIGHT_SPEED_MULT = 0.1
